### ISSUE TITLE
where did you get the CADL/data/pokemon/jpeg files? can they be included in repo?

### ISSUE THREAD

**Issue by johndpope** [niazangels/vae-pokedex#1]
I know siraj mentioned this training set. 
was there a reason you didn't try simply spitting out one character instead of dozens at same time?

**Comment by niazangels** [comment]
Hi @johndpope ,
I found this forum had a good set of images and went ahead with it: http://pokemonhackersonline.com/showthread.php?t=13390 

You can download them directly from here:
http://www.mediafire.com/file/dkm8kh5uxo12bzy/BWBW2+64x64+Sprites.zip

I had to crop each images into 4 images using Imagemagick.

I generated each character individually. The montage just concatenates all of them together to produce a 10x10 pokemon image. You can just try 

```
fig, axs = plt.subplots(1, 2, figsize=(10, 10))

axs[0].imshow(test_images[0])
axs[0].set_title('Original')

axs[1].imshow(recon[0])
axs[1].set_title('Synthesis')

fig.canvas.draw()

plt.show()
```
to see just the first reconstructed image.
