### ISSUE TITLE
data set

### ISSUE THREAD

**Issue by ehfo0** [niazangels/vae-pokedex#2]
hi
would u add the  pokemon data set to you jupyter note book or add a link to download it pls?
the dimension of the image I downloaded is (1, 651, 1041, 3)!
I GOT it from [https://imgur.com/Mbon0yD](url)

**Comment by niazangels** [comment]
Okay, let me do that for you.

**Comment by niazangels** [comment]
Dataset added! Hope this was helpful.
Have fun!

**Comment by ehfo0** [comment]
@Thank u!
